name: biz_analytics_a
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - cookiecutter=1.7.3
  - jupyterlab=3.3.2
  - matplotlib=3.3.1
  - pandas=1.1.3
  - pip=20.2.4
  - plotly=4.11.0
  - pytest=7.1.1
  - python=3.8.5
  - py-xgboost=1.5.1
  - requests=2.24.0
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - yellowbrick=1.3
  - pip:
    - streamlit==1.7.0
